src/ui.rs

Users with tiling window managers may prefer to hide window decorations to save vertical space. By overriding NVIM_GTK_NO_HEADERBAR=1, no client side decorations or tool bar icons are drawn.
`header_bar` is no longer part of `ui::Components` since it's not referenced outside of `Ui::init`.
The application menu is only created if requested by the desktop environment to avoid creation of an additional menu bar with nothing but the "About" item.

Optionally disable header bars with NVIM_GTK_NO_HEADERBAR=1

---

desktop/org.daa.NeovimGtk.desktop

Copied `MimeType` line from `nvim.desktop` which copied it from `gvim.desktop`.

Add MIME types to desktop file

---

src/ui.rs

Allow users to use the dark theme variant by setting `NVIM_GTK_PREFER_DARK_THEME=1`.

Introduce option to prefer dark GTK theme

---

src/main.rs
src/ui.rs

These are two weakly related changes:
- Set `APPLICATION_NON_UNIQUE`.
This causes the application to start new instances in their own processes instead of using the primary instance for all windows. I feel this is a more natural behaviour for vim as the instances aren't really related. It also has the advantage, that crashing instances don't crash other instances and that new instances correctly set their current working directory to the one they were started from instead of reusing the cwd of the primary instance.
-  Introduce `new-window` action.
Add a "New Window" entry to the menu. Also, Gnome checks for this action when [trying to figure out whether the application can open a new window](https://github.com/GNOME/gnome-shell/blob/master/src/shell-app.c#L576-L583). For example the …

Introduce new-window action, set non_unique

---

src/theme.rs

I use a color scheme ([hybrid](https://github.com/w0ng/vim-hybrid)), where `Pmenu` and `PmenuSel` are identical except `PmenuSel` sets `reverse`. On the popup menu, this causes the selected line to be indistinguishable from the unselected ones.
I don't know if this code makes sense at this place, but it fixes the issue for me.

Fix popup colors not being reversed

---

runtime/plugin/nvim_gui_shim.vim
src/nvim/handler.rs
src/nvim/redraw_handler.rs
src/shell.rs

Hi, just discovered this project recently, ligatures and native completion popups are great, I'm actually looking into switching from tmux + neovim in terminal to this + terminals in neovim :)
To avoid xclip usage on Wayland and to improve potential remote usage, it would be nice to have native gtk clipboard support. Here's my attempt :)
- Can't have the UI borrowed mutably when waiting for the clipboard text, so I had to push the mutex locking down into the request handlers to be able to make the borrows work for the clipboard get command;
- Using an `mpsc` channel basically as a future, to avoid extra dependencies; 
- I've tried placing the clipboard function into `runtime/autoload/providers/clipboard.vim`, but it didn't load for some reason

Add RPC/GTK clipboard provider

---

runtime/plugin/nvim_gui_shim.vim
src/nvim/redraw_handler.rs
src/shell.rs

- Added `PRIMARY` support (please test, I'm currenty running Wayland where it's not a thing)
- "Fixed" `yy` line copying (by storing the last register type — this is mostly fine, but e.g. pasting from other apps after copying lines would paste as lines)
Actually, register type should be stored in the GTK clipboard, like in good old GVim. I'm looking into this, including https://github.com/gtk-rs/gtk/issues/591

GTK clipboard part 2

---

resources/side-panel.ui
src/file_browser.rs
src/main.rs
src/ui.rs

Finally got back to it. Changes compared to last time are:
- Adapted the design to closer match Gnome Builder:
- No expander arrows.
- Directories are expanded, not opened, with single clicks.
- Swapped the toolbar for a ComboBox with the components of the cwd path.
- Sidebar is hidden by default.
- Visibility state and width are restored at startup.

Introduce sidebar with file browser

---

src/file_browser.rs
src/plug_manager/vim_plug.rs
src/shell.rs
src/subscriptions.rs
src/tabline.rs

Pretty much what the title says.
The reason for my original problem turned out to be the call to `nvim.eval()` from `connect_row_activated()`, but I guess this doesn't hurt.
The problem I observed was a hang-up when calling `:ls` and then clicking an entry of the file tree without closing the output by hitting return first.

Use nvim.command_async where possible

---

src/main.rs
src/nvim/mod.rs
src/shell.rs

When NeovimGTK is opened with multiple files, don't spawn a separate instance for each file, but open them all via Vim's argument list.
I couldn't find how to get rid of the original unnamed buffer, however.
The code in `connect_drag_data_received()` is just reformatted.

Open multiple files in one instance

---

src/file_browser.rs

The directory chooser on top of the file tree had a bug where it would trigger another directory change for each directory change. When directories are changed quickly, e.g. by a plugin or fast scrolling on top of the directory chooser, this triggers an infinite loop, resulting in a lockup of the application.

Fix bug where rapid `cd`s cause infinite loop

---

src/project.rs

These are not really clear improvements, but changes I like. The changes are:
- Entries are activated by single click (except when clicking the favorite checkboxes).
- Entries are selected (highlighted) on hover for visual cue.
- Entries are separated with grid lines.
- Paddings and size slightly changed.
- Font size for filename reduced.
What I would have liked, but not yet done is to include a style sheet to
- handle font sizes,
- make directory names slightly grayed out as in Gedit, and
- handle hover effects, maybe theme dependent to be more subtle than the selection effect.
If you like some of the changes, I am happy to adapt the pull request.

Single click activation on projects popover

---

src/project.rs
src/settings.rs
src/shell_dlg.rs

Writing to `stdout` will panic if the pipe is broken. This can happen, for example, if you run (in Linux):
```sh
nvim-gtk & exit
```
Then repeatedly hit `<Tab>`  to make it print `Event bell([])` to the (already closed) `STDOUT`. After a few tabs it'll crash - because it is trying to write to a broken pipe.
The macros from the `log` crate don't crash when the pipe is broken. It also makes more sense to use them, since these prints are not the actual _output_ of the application.

Use `error!`/`warn!` logs instead of `println!`

---

src/main.rs
src/nvim/mod.rs
src/shell.rs

This allows some more advanced workflows, such as:
* Run with the default configuration:
```bash
nvim-gtk -- -u NONE
```
* Diff between two files:
```bash
nvim-gtk -- -d file1 file2
```
* Run commands:
```bash
nvim-gtk -- -s speacial_preparations.vim
```
And more.

Pass arguments after `--` directly to Neovim

---

README.md

I had to discover the exact packages to install when trying this project out, so I thought I'd document them in the README.
Adding an equivalent section for Red Hat-derived distributions too sounds like a good idea, perhaps in a future PR.

Mention the Debian/Ubuntu GTK dev packages in README

---

README.md

So that it's easier for people using Fedora to build the project.

Added Fedora dependencies to the README

---

src/ui.rs

This is actually a small change and ensures that there are no decorations when headerbar is disabled. Is this the intended behavior? Or maybe this should be a different option altogether?

[RFC] unset decorated flag when NVIM_GTK_NO_HEADERBAR=1

---

src/ui.rs

This introduces NVIM_GTK_NO_WINDOW_DECORATION to control window
decoration, allowing to disable the header bar without disabling window
decorations.

Control window decorations with it's own flag

---

Makefile

The DESTDIR variable is usually set when a piece of software is being
packaged. It tells the installation script that it should place its
files to a specific directory while not affecting PREFIX.

Make installation repsect DESTDIR

---

desktop/org.daa.NeovimGtk-symbolic.svg

The first part of the N in the symbolic version of the logo was not
being showed as empty or transparent as styled on the official logos.
That wasn't because of the no-fill property for that shape on the SVG
file missing to be set but because GNOME fills any polygon shape when
drawing icons on the top-bar.
The solution was to replace the strikes of that specific shape with
separate lines not forming a polygon but coinciding on their vertices.

Correct symbolic version of the icon

---

Makefile

Also, add missing .PHONY target.
Also, in my opinion a text editor has no business to install fonts to my system. If we require a font, then we should say so in README, or raise an error when it is missing, but not install it on our own.
Fixes #164

Don't use -i option for sed to make it more compatible with non-GNU sed.

---

src/tabline.rs

More of an aesthetic improvement. But pretty much all Gnome apps do this, so I guess this PR improves HIG compliance.

Expand tabs to fill tabline

---

Cargo.toml
src/main.rs

So different users can use nvim-gtk w/o conflicting.

Add the username to log name

---

Cargo.lock
appveyor.yml
src/cmd_line.rs
src/file_browser.rs
src/highlight.rs
src/main.rs
src/nvim/redraw_handler.rs
src/plug_manager/plugin_settings_dlg.rs
src/plug_manager/ui.rs
src/plug_manager/vim_plug.rs
src/popup_menu.rs
src/project.rs
src/render/model_clip_iterator.rs
src/shell.rs
src/subscriptions.rs
src/tabline.rs
src/ui.rs
src/ui_model/item.rs
src/ui_model/line.rs
src/ui_model/model_rect.rs

- Just some minor code style improvements.
- Updated Rust version to 1.38, because otherwise AppVeyor was failing over `whoami` crate (was 1.33).
- Updated the dependencies

Clippy fixes

---

src/render/context.rs
src/render/mod.rs

Fixes #250
Left is before, right is after:

Fix underlines/undercurl rendering

---

src/highlight.rs
src/render/context.rs
src/render/mod.rs

Top is before, bottom is after:
Fixes #249

Add support for strikethrough

---

README.md

There is no need to install all the libs mentioned since pulling only from `libgtk-3-dev` installs everything else as a dependency.

Update README with Debian install instructions

---

runtime/plugin/nvim_gui_shim.vim
src/cursor.rs
src/nvim/redraw_handler.rs
src/shell.rs

`:NGSetCursorBlink` can set the number of times the cursor blinks before stopping or disable the cursor blinking entirely. If the value passed in is negative, the cursor won't stop blinking, and if it's zero, the cursor won't blink.
I'm a newbie at both Rust and Vim, so I'm not sure if this is the best way of implementing the option. Thanks!!

Adds an option to change cursor blinking
